<?php
/*********************************************CAMPOS IMPO ************************************************************************************/
$camposSismarImp[] = array('campo'=>"sob.numero_bl", 'nombre'=>_TABNUMEROBL, 'alias'=>'numero_bl', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"DATE_FORMAT(sob.fecha, '%Y-%m')", 'nombre'=>_TABFECHA, 'alias'=>'periodo', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"DATE_FORMAT(sob.fecha, '%Y-%m-%d')", 'nombre'=>_TABFECHAYMD, 'alias'=>'periodoymd', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"clase_bl.clase_bl", 'nombre'=>_TABCLASEBL, 'alias'=>'clase_bl', 'key'=>'sob.id_clase_bl', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"estado_bl.estado_bl", 'nombre'=>_TABESTADOBL, 'alias'=>'estado_bl', 'key'=>'sob.id_estado_bl', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"sob.id_empresa", 'nombre'=>_TABNIT, 'alias'=>'id_empresa', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"empresa.digito_chequeo", 'nombre'=>_TABDIGCHEQ, 'alias'=>'digito_chequeo', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"empresa.empresa", 'nombre'=>_TABEMPRESAI, 'alias'=>'empresa', 'key'=>'sob.id_empresa', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"empresa.ciudad", 'nombre'=>_TABCIUDAD, 'alias'=>'ciudad', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"empresa.departamento", 'nombre'=>_TABDEPTO, 'alias'=>'departamento', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"empresa.telefono", 'nombre'=>_TABTELE, 'alias'=>'telefono', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"empresa.representante", 'nombre'=>_TABREPRES, 'alias'=>'representante', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"empresa.direccion", 'nombre'=>_TABDIRECCION, 'alias'=>'direccion', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"empresa.fax", 'nombre'=>_TABFAX, 'alias'=>'fax', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"empresa.email", 'nombre'=>_TABEMAIL, 'alias'=>'email', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"empresa_ext.empresa_ext", 'nombre'=>_TABEMPRESAEXT, 'alias'=>'empresa_ext', 'key'=>'sob.id_empresa_ext', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"naviera.naviera", 'nombre'=>_TABNAVIERA, 'alias'=>'naviera', 'key'=>'sob.id_naviera', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"agente_naviero.agente_naviero", 'nombre'=>_TABAGENTENAV, 'alias'=>'agente_naviero', 'key'=>'sob.id_agente_naviero', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"motonave.motonave", 'nombre'=>_TABMOTONAVE, 'alias'=>'motonave', 'key'=>'sob.id_motonave', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"consolidador.consolidador", 'nombre'=>_TABCONSOLI, 'alias'=>'consolidador', 'key'=>'sob.id_consolidador', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"consolidador_nieto.consolidador", 'nombre'=>_TABCONSOLINIETO, 'alias'=>'consolidador_nieto', 'key'=>'sob.id_consolidador_nieto', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"consolidado.consolidado", 'nombre'=>_TABCONSOLIDADO, 'alias'=>'consolidado', 'key'=>'sob.id_consolidado', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"otm.otm", 'nombre'=>_TABOTM, 'alias'=>'otm', 'key'=>'sob.id_otm', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"puerto.puerto", 'nombre'=>_TABPUERTO, 'alias'=>'puerto', 'key'=>'sob.id_puerto', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"muelle.muelle", 'nombre'=>_TABMUELLE, 'alias'=>'muelle', 'key'=>'sob.id_muelle', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"pais_puerto_ext.paises", 'nombre'=>_TABPAISPTOEXT, 'alias'=>'pais_puerto_ext', 'key'=>'sob.id_pais_puerto_ext', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"puerto_ext.ciudad", 'nombre'=>_TABPTOEXT, 'alias'=>'puerto_ext', 'key'=>'sob.id_puerto_ext', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"puerto_transbordo.ciudad", 'nombre'=>_TABPTOTRANS, 'alias'=>'puerto_transbordo', 'key'=>'sob.id_puerto_transbordo', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"ciudad_pro_dest_pais.ciudad", 'nombre'=>_TABCIUPRODESTCOL, 'alias'=>'ciudad_pro_dest_pais', 'key'=>'sob.id_ciudad_pro_dest_pais', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"depto_pro_dest_pais.departamento", 'nombre'=>_TABDEPTOPRODESTCOL, 'alias'=>'depto_pro_dest_pais', 'key'=>'sob.id_depto_pro_dest_pais', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"sob.descripcion_prod", 'nombre'=>_TABDESCRIPCIONBL, 'alias'=>'descripcion_prod', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>1,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"sob.id_subpartida", 'nombre'=>_TABSUBPARTIDA, 'alias'=>'id_subpartida', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"subpartida.subpartida", 'nombre'=>_TABDESCRIPCIONSUB, 'alias'=>'subpartida', 'key'=>'sob.id_subpartida', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"sob.id_capitulo", 'nombre'=>_TABCAPITULO, 'alias'=>'id_capitulo', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"capitulo.capitulo", 'nombre'=>_TABDESCRIPCIONCAP, 'alias'=>'capitulo', 'key'=>'sob.id_capitulo', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"sob.cantidad", 'nombre'=>_TABCANTIDADD, 'alias'=>'cantidad', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"embalaje.embalaje", 'nombre'=>_TABUNIDAD, 'alias'=>'embalaje', 'key'=>'sob.id_embalaje', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"sob.kilos", 'nombre'=>_TABKILOS, 'alias'=>'kilos', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"sob.cantidad_estiba", 'nombre'=>_TABCANTEST, 'alias'=>'cantidad_estiba', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"tipo_estiba.tipo_estiba", 'nombre'=>_TABTIPOEST, 'alias'=>'tipo_estiba', 'key'=>'sob.id_tipo_estiba', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"sob.teus", 'nombre'=>_TABTEUS, 'alias'=>'teus', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"sob.feus", 'nombre'=>_TABFEUS, 'alias'=>'feus', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"(sob.teus + (sob.feus * 2))", 'nombre'=>_TABGRANTOTALTEUS, 'alias'=>'gran_total_teus', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"(sob.feus + (sob.teus / 2))", 'nombre'=>_TABGRANTOTALFEUS, 'alias'=>'gran_total_feus', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"sob.teus_fcl", 'nombre'=>_TABTEUSFCL, 'alias'=>'teus_fcl', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"sob.feus_fcl", 'nombre'=>_TABFEUSFCL, 'alias'=>'feus_fcl', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"sob.gran_total_teus_fcl", 'nombre'=>_TABGRANTOTALTEUSFCL, 'alias'=>'gran_total_teus_fcl', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"sob.teus_lcl", 'nombre'=>_TABTEUSLCL, 'alias'=>'teus_lcl', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"sob.feus_lcl", 'nombre'=>_TABFEUSLCL, 'alias'=>'feus_lcl', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"sob.gran_total_teus_lcl", 'nombre'=>_TABGRANTOTALTEUSLCL, 'alias'=>'gran_total_teus_lcl', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"intermediario_pais.intermediario_pais", 'nombre'=>_TABEMPRESANOTIFICADA, 'alias'=>'intermediario_pais', 'key'=>'sob.id_intermediario_pais', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"sob.numero_bl_nieto", 'nombre'=>_TABNUMEROBLNIETO, 'alias'=>'numero_bl_nieto', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"transito.transito", 'nombre'=>_TABTRANSITO, 'alias'=>'transito', 'key'=>'sob.id_transito', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"ciudad_pro_dest_ext.ciudad", 'nombre'=>_TABCIUPRODESTEXT, 'alias'=>'ciudad_pro_dest_ext', 'key'=>'sob.id_ciudad_pro_dest_ext', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"pais_ciudad_pro_dest_ext.paises", 'nombre'=>_TABPAISCIUPRODESTEXT, 'alias'=>'pais_ciudad_pro_dest_ext', 'key'=>'sob.id_pais_ciudad_pro_dest_ext', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"sia.sia", 'nombre'=>_TABSIA, 'alias'=>'sia', 'key'=>'sob.id_sia', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"deposito.deposito", 'nombre'=>_TABDEPOSITO, 'alias'=>'deposito', 'key'=>'sob.id_deposito', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"zona_franca.zona_franca", 'nombre'=>_TABZONAF, 'alias'=>'zona_franca', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"clase_flete.clase_flete", 'nombre'=>_TABCLASFLETE, 'alias'=>'clase_flete', 'key'=>'sob.id_clase_flete', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"tipo_bl.tipo_bl", 'nombre'=>_TABTIPOBL, 'alias'=>'tipo_bl', 'key'=>'sob.id_tipo_bl', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"ciiu.ciiu", 'nombre'=>_TABCIIU, 'alias'=>'ciiu', 'key'=>'sob.id_ciiu', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"cuode.cuode", 'nombre'=>_TABCUODE, 'alias'=>'cuode', 'key'=>'sob.id_cuode', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarImp[] = array('campo'=>"sob.sobordo", 'nombre'=>_TABSOBORDO, 'alias'=>'sobordo', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"sob.consecutivo", 'nombre'=>_TABCONSECUTIVO, 'alias'=>'consecutivo', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"sob.revista_diaria", 'nombre'=>_TABREVISTADIARIA, 'alias'=>'revista_diaria', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarImp[] = array('campo'=>"sob.revista_semanal", 'nombre'=>_TABREVISTASEMANAL, 'alias'=>'revista_semanal', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);

/*********************************************CAMPOS EXPO ************************************************************************************/

$camposSismarExp[] = array('campo'=>"sob.numero_bl", 'nombre'=>_TABNUMEROBL, 'alias'=>'numero_bl', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"clase_bl.clase_bl", 'nombre'=>_TABCLASEBL, 'alias'=>'clase_bl', 'key'=>'sob.id_clase_bl', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"estado_bl.estado_bl", 'nombre'=>_TABESTADOBL, 'alias'=>'estado_bl', 'key'=>'sob.id_estado_bl', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"DATE_FORMAT(sob.fecha, '%Y-%m')", 'nombre'=>_TABFECHA, 'alias'=>'periodo', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"DATE_FORMAT(sob.fecha, '%Y-%m-%d')", 'nombre'=>_TABFECHAYMD, 'alias'=>'periodoymd', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"sob.id_empresa", 'nombre'=>_TABNIT, 'alias'=>'id_empresa', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"empresa.digito_chequeo", 'nombre'=>_TABDIGCHEQ, 'alias'=>'digito_chequeo', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"empresa.empresa", 'nombre'=>_TABEMPRESAE, 'alias'=>'empresa', 'key'=>'sob.id_empresa', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"empresa.ciudad", 'nombre'=>_TABCIUDAD, 'alias'=>'ciudad', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"empresa.departamento", 'nombre'=>_TABDEPTO, 'alias'=>'departamento', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"empresa.telefono", 'nombre'=>_TABTELE, 'alias'=>'telefono', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"empresa.representante", 'nombre'=>_TABREPRES, 'alias'=>'representante', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"empresa.direccion", 'nombre'=>_TABDIRECCION, 'alias'=>'direccion', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"empresa.fax", 'nombre'=>_TABFAX, 'alias'=>'fax', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"empresa.email", 'nombre'=>_TABEMAIL, 'alias'=>'email', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"empresa_ext.empresa_ext", 'nombre'=>_TABEMPRESAEXT, 'alias'=>'empresa_ext', 'key'=>'sob.id_empresa_ext', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"naviera.naviera", 'nombre'=>_TABNAVIERA, 'alias'=>'naviera', 'key'=>'sob.id_naviera', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"agente_naviero.agente_naviero", 'nombre'=>_TABAGENTENAV, 'alias'=>'agente_naviero', 'key'=>'sob.id_agente_naviero', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"motonave.motonave", 'nombre'=>_TABMOTONAVE, 'alias'=>'motonave', 'key'=>'sob.id_motonave', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"consolidador.consolidador", 'nombre'=>_TABCONSOLI, 'alias'=>'consolidador', 'key'=>'sob.id_consolidador', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"consolidador_nieto.consolidador", 'nombre'=>_TABCONSOLINIETO, 'alias'=>'consolidador_nieto', 'key'=>'sob.id_consolidador_nieto', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"consolidado.consolidado", 'nombre'=>_TABCONSOLIDADO, 'alias'=>'consolidado', 'key'=>'sob.id_consolidado', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"otm.otm", 'nombre'=>_TABOTM, 'alias'=>'otm', 'key'=>'sob.id_otm', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"puerto.puerto", 'nombre'=>_TABPUERTO, 'alias'=>'puerto', 'key'=>'sob.id_puerto', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"muelle.muelle", 'nombre'=>_TABMUELLE, 'alias'=>'muelle', 'key'=>'sob.id_muelle', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"pais_puerto_ext.paises", 'nombre'=>_TABPAISPTOEXT, 'alias'=>'pais_puerto_ext', 'key'=>'sob.id_pais_puerto_ext', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"puerto_ext.ciudad", 'nombre'=>_TABPTOEXT, 'alias'=>'puerto_ext', 'key'=>'sob.id_puerto_ext', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"puerto_transbordo.ciudad", 'nombre'=>_TABPTOTRANS, 'alias'=>'puerto_transbordo', 'key'=>'sob.id_puerto_transbordo', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"ciudad_pro_dest_pais.ciudad", 'nombre'=>_TABCIUPRODESTCOL, 'alias'=>'ciudad_pro_dest_pais', 'key'=>'sob.id_ciudad_pro_dest_pais', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"depto_pro_dest_pais.departamento", 'nombre'=>_TABDEPTOPRODESTCOL, 'alias'=>'depto_pro_dest_pais', 'key'=>'sob.id_depto_pro_dest_pais', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"sob.descripcion_prod", 'nombre'=>_TABDESCRIPCIONBL, 'alias'=>'descripcion_prod', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>1,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"sob.id_subpartida", 'nombre'=>_TABSUBPARTIDA, 'alias'=>'id_subpartida', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"subpartida.subpartida", 'nombre'=>_TABDESCRIPCIONSUB, 'alias'=>'subpartida', 'key'=>'sob.id_subpartida', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"sob.id_capitulo", 'nombre'=>_TABCAPITULO, 'alias'=>'id_capitulo', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"capitulo.capitulo", 'nombre'=>_TABDESCRIPCIONCAP, 'alias'=>'capitulo', 'key'=>'sob.id_capitulo', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"sob.cantidad", 'nombre'=>_TABCANTIDADD, 'alias'=>'cantidad', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"embalaje.embalaje", 'nombre'=>_TABUNIDAD, 'alias'=>'embalaje', 'key'=>'sob.id_embalaje', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"sob.cantidad_estiba", 'nombre'=>_TABCANTEST, 'alias'=>'cantidad_estiba', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"tipo_estiba.tipo_estiba", 'nombre'=>_TABTIPOEST, 'alias'=>'tipo_estiba', 'key'=>'sob.id_tipo_estiba', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"sob.kilos", 'nombre'=>_TABKILOS, 'alias'=>'kilos', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"sob.teus", 'nombre'=>_TABTEUS, 'alias'=>'teus', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"sob.feus", 'nombre'=>_TABFEUS, 'alias'=>'feus', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"(sob.teus + (sob.feus * 2))", 'nombre'=>_TABGRANTOTALTEUS, 'alias'=>'gran_total_teus', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"(sob.feus + (sob.teus / 2))", 'nombre'=>_TABGRANTOTALFEUS, 'alias'=>'gran_total_feus', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"sob.teus_fcl", 'nombre'=>_TABTEUSFCL, 'alias'=>'teus_fcl', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"sob.feus_fcl", 'nombre'=>_TABFEUSFCL, 'alias'=>'feus_fcl', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"sob.gran_total_teus_fcl", 'nombre'=>_TABGRANTOTALTEUSFCL, 'alias'=>'gran_total_teus_fcl', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"sob.teus_lcl", 'nombre'=>_TABTEUSLCL, 'alias'=>'teus_lcl', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"sob.feus_lcl", 'nombre'=>_TABFEUSLCL, 'alias'=>'feus_lcl', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"sob.gran_total_teus_lcl", 'nombre'=>_TABGRANTOTALTEUSLCL, 'alias'=>'gran_total_teus_lcl', 'key'=>'', 'tipo'=>'n', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"intermediario_pais.intermediario_pais", 'nombre'=>_TABEMPRESANOTIFICADA, 'alias'=>'intermediario_pais', 'key'=>'sob.id_intermediario_pais', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"sob.numero_bl_nieto", 'nombre'=>_TABNUMEROBLNIETO, 'alias'=>'numero_bl_nieto', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"transito.transito", 'nombre'=>_TABTRANSITO, 'alias'=>'transito', 'key'=>'sob.id_transito', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"ciudad_pro_dest_ext.ciudad", 'nombre'=>_TABCIUPRODESTEXT, 'alias'=>'ciudad_pro_dest_ext', 'key'=>'sob.id_ciudad_pro_dest_ext', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"pais_ciudad_pro_dest_ext.paises", 'nombre'=>_TABPAISCIUPRODESTEXT, 'alias'=>'pais_ciudad_pro_dest_ext', 'key'=>'sob.id_pais_ciudad_pro_dest_ext', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"sia.sia", 'nombre'=>_TABSIA, 'alias'=>'sia', 'key'=>'sob.id_sia', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"deposito.deposito", 'nombre'=>_TABDEPOSITO, 'alias'=>'deposito', 'key'=>'sob.id_deposito', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"zona_franca.zona_franca", 'nombre'=>_TABZONAF, 'alias'=>'zona_franca', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"clase_flete.clase_flete", 'nombre'=>_TABCLASFLETE, 'alias'=>'clase_flete', 'key'=>'sob.id_clase_flete', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"tipo_bl.tipo_bl", 'nombre'=>_TABTIPOBL, 'alias'=>'tipo_bl', 'key'=>'sob.id_tipo_bl', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"sob.sobordo", 'nombre'=>_TABSOBORDO, 'alias'=>'sobordo', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"sob.consecutivo", 'nombre'=>_TABCONSECUTIVO, 'alias'=>'consecutivo', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"sob.revista_diaria", 'nombre'=>_TABREVISTADIARIA, 'alias'=>'revista_diaria', 'key'=>'', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"sob.revista_semanal", 'nombre'=>_TABREVISTASEMANAL, 'alias'=>'revista_semanal', 'key'=>'', 'tipo'=>'s', 'sort'=>0, 'groupby'=>0, 'fulltext'=>0,'enacumulado'=>0);
$camposSismarExp[] = array('campo'=>"ciiu.ciiu", 'nombre'=>_TABCIIU, 'alias'=>'ciiu', 'key'=>'sob.id_ciiu', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);
$camposSismarExp[] = array('campo'=>"cuode.cuode", 'nombre'=>_TABCUODE, 'alias'=>'cuode', 'key'=>'sob.id_cuode', 'tipo'=>'s', 'sort'=>1, 'groupby'=>1, 'fulltext'=>0,'enacumulado'=>1);



$camposIntercambioSismar[0] = $camposSismarImp;
$camposIntercambioSismar[1] = $camposSismarExp;


$agruparSismarImp[_TOTALES] = array('sob.teus', 'sob.feus', '(sob.teus + (sob.feus * 2))', '(sob.feus + (sob.teus / 2))', 'sob.teus_fcl', 'sob.feus_fcl', '(sob.teus_fcl + (sob.feus_fcl * 2))', 'sob.teus_lcl', 'sob.feus_lcl', '(sob.feus_fcl + (sob.teus_fcl / 2))', 'sob.cantidad', 'sob.kilos', 'sob.cantidad_estiba');
$agruparSismarExp[_TOTALES] = array('sob.teus', 'sob.feus', '(sob.teus + (sob.feus * 2))', '(sob.feus + (sob.teus / 2))', 'sob.teus_fcl', 'sob.feus_fcl', '(sob.teus_fcl + (sob.feus_fcl * 2))', 'sob.teus_lcl', 'sob.feus_lcl', '(sob.feus_fcl + (sob.teus_fcl / 2))', 'sob.cantidad', 'sob.kilos', 'sob.cantidad_estiba');



$filtrosSismarImp[] = array('campo'=>'sob.id_anio', 'alias'=>'id_anio', 'filtro'=>FILTRO_ANIO, 'tabla'=>'anio', 'nombre'=>_ANIO, 'opcional'=>0, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.fecha', 'alias'=>'fecha', 'filtro'=>FILTRO_PERIODODESDEDIA, 'tabla'=>'', 'nombre'=>_DESDE, 'opcional'=>0, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.fecha', 'alias'=>'fecha', 'filtro'=>FILTRO_PERIODOHASTADIA, 'tabla'=>'', 'nombre'=>_HASTA, 'opcional'=>0, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_clase_bl', 'alias'=>'id_clase_bl', 'filtro'=>FILTRO_CLASEBL, 'tabla'=>'clase_bl', 'nombre'=>_TABCLASEBL, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_estado_bl', 'alias'=>'id_estado_bl', 'filtro'=>FILTRO_ESTADOBL, 'tabla'=>'estado_bl', 'nombre'=>_TABESTADOBL, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_empresa', 'alias'=>'id_empresa', 'filtro'=>FILTRO_NIT, 'tabla'=>'empresa', 'nombre'=>_NIT, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'empresa.id_ciudad', 'alias'=>'emp_id_ciudad', 'filtro'=>FILTRO_CIUDAD, 'tabla'=>'ciudad', 'nombre'=>_TABCIUDAD, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarImp[] = array('campo'=>'empresa.id_departamento', 'alias'=>'emp_id_departamento', 'filtro'=>FILTRO_DEPARTAMENTO, 'tabla'=>'departamento', 'nombre'=>_TABDEPTO, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarImp[] = array('campo'=>'sob.id_intermediario_pais', 'alias'=>'id_intermediario_pais', 'filtro'=>FILTRO_EMPRESANOTIFICADA, 'tabla'=>'intermediario_pais', 'nombre'=>_TABEMPRESANOTIFICADA, 'opcional'=>1, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_puerto', 'alias'=>'id_puerto', 'filtro'=>FILTRO_PUERTO, 'tabla'=>'puerto', 'nombre'=>_TABPUERTO, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_muelle', 'alias'=>'id_muelle', 'filtro'=>FILTRO_MUELLE, 'tabla'=>'muelle', 'nombre'=>_TABMUELLE, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_pais_puerto_ext', 'alias'=>'id_pais_puerto_ext', 'filtro'=>FILTRO_SOLOPAIS, 'tabla'=>'paises', 'nombre'=>_TABPAISPTOEXT, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarImp[] = array('campo'=>'sob.id_puerto_ext', 'alias'=>'id_puerto_ext', 'filtro'=>FILTRO_PAISPUERTOEXT, 'tabla'=>'ciudad', 'nombre'=>_TABPTOEXT, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarImp[] = array('campo'=>'sob.id_naviera', 'alias'=>'id_naviera', 'filtro'=>FILTRO_NAVIERA, 'tabla'=>'naviera', 'nombre'=>_TABNAVIERA, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarImp[] = array('campo'=>'sob.id_agente_naviero', 'alias'=>'id_agente_naviero', 'filtro'=>FILTRO_AGENTENAVIERO, 'tabla'=>'agente_naviero', 'nombre'=>_TABAGENTENAV, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_motonave', 'alias'=>'id_motonave', 'filtro'=>FILTRO_MOTONAVE, 'tabla'=>'motonave', 'nombre'=>_TABMOTONAVE, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_consolidador', 'alias'=>'id_consolidador', 'filtro'=>FILTRO_CONSOLIDADOR, 'tabla'=>'consolidador', 'nombre'=>_TABCONSOLI, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_consolidado', 'alias'=>'id_consolidado', 'filtro'=>FILTRO_CONSOLIDADO, 'tabla'=>'consolidado', 'nombre'=>_TABCONSOLIDADO, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarImp[] = array('campo'=>'sob.id_otm', 'alias'=>'id_otm', 'filtro'=>FILTRO_OTM, 'tabla'=>'otm', 'nombre'=>_TABOTM, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_empresa_ext', 'alias'=>'id_empresa_ext', 'filtro'=>FILTRO_EMPRESAEXT, 'tabla'=>'empresa_ext', 'nombre'=>_TABEMPRESAEXT, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_ciudad_pro_dest_ext', 'alias'=>'id_ciudad_pro_dest_ext', 'filtro'=>FILTRO_CIUDADPRODESTEXT, 'tabla'=>'ciudad', 'nombre'=>_TABCIUPRODESTEXT, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarImp[] = array('campo'=>'sob.id_tipo_estiba', 'alias'=>'id_tipo_estiba', 'filtro'=>FILTRO_TIPOESTIBA, 'tabla'=>'tipo_estiba', 'nombre'=>_TABTIPOEST, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_embalaje', 'alias'=>'id_embalaje', 'filtro'=>FILTRO_EMBALAJE, 'tabla'=>'embalaje', 'nombre'=>_TABUNIDAD, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_subpartida', 'alias'=>'id_subpartida', 'filtro'=>FILTRO_CODARMONIZADO, 'tabla'=>'subpartida', 'nombre'=>_CODARMONIZADO, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_bigint');
$filtrosSismarImp[] = array('campo'=>'sob.descripcion_prod', 'alias'=>'descripcion_prod', 'filtro'=>FILTRO_DESCRIPCIONPROD, 'tabla'=>'fulltext', 'nombre'=>_TABDESCRIPCIONBL, 'opcional'=>1, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_ciudad_pro_dest_pais', 'alias'=>'id_ciudad_pro_dest_pais', 'filtro'=>FILTRO_CIUDADPRODEST, 'tabla'=>'ciudad', 'nombre'=>_TABCIUPRODESTCOL, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarImp[] = array('campo'=>'sob.id_depto_pro_dest_pais', 'alias'=>'id_depto_pro_dest_pais', 'filtro'=>FILTRO_DEPTOPRODESTCOL, 'tabla'=>'departamento', 'nombre'=>_TABDEPTOPRODESTCOL, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarImp[] = array('campo'=>'sob.id_tipo_bl', 'alias'=>'id_tipo_bl', 'filtro'=>FILTRO_TIPOBL, 'tabla'=>'tipo_bl', 'nombre'=>_TABTIPOBL, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
//$filtrosSismarImp[] = array('campo'=>'sob.id_puerto', 'alias'=>'id_puerto', 'filtro'=>FILTRO_SOLOPUERTO, 'tabla'=>'puerto', 'nombre'=>_PUERTO, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_clase_flete', 'alias'=>'id_clase_flete', 'filtro'=>FILTRO_CLASEFLETE, 'tabla'=>'clase_flete', 'nombre'=>_TABCLASFLETE, 'opcional'=>1, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarImp[] = array('campo'=>'sob.id_transito', 'alias'=>'id_transito', 'filtro'=>FILTRO_TRANSITO, 'tabla'=>'transito', 'nombre'=>_TABTRANSITO, 'opcional'=>1, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_zona_franca', 'alias'=>'id_zona_franca', 'filtro'=>FILTRO_ZONAFRANCA, 'tabla'=>'zona_franca', 'nombre'=>_TABZONAF, 'opcional'=>1, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_ciiu', 'alias'=>'id_ciiu', 'filtro'=>FILTRO_CIIU, 'tabla'=>'ciiu', 'nombre'=>_CIIU, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarImp[] = array('campo'=>'sob.id_cuode', 'alias'=>'id_cuode', 'filtro'=>FILTRO_CUODE, 'tabla'=>'cuode', 'nombre'=>_CUODE, 'opcional'=>1, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');


$filtrosSismarExp[] = array('campo'=>'sob.id_anio', 'alias'=>'id_anio', 'filtro'=>FILTRO_ANIO, 'tabla'=>'anio', 'nombre'=>_ANIO, 'opcional'=>0, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.fecha', 'alias'=>'fecha', 'filtro'=>FILTRO_PERIODODESDEDIA, 'tabla'=>'', 'nombre'=>_DESDE, 'opcional'=>0, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.fecha', 'alias'=>'fecha', 'filtro'=>FILTRO_PERIODOHASTADIA, 'tabla'=>'', 'nombre'=>_HASTA, 'opcional'=>0, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_clase_bl', 'alias'=>'id_clase_bl', 'filtro'=>FILTRO_CLASEBL, 'tabla'=>'clase_bl', 'nombre'=>_TABCLASEBL, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_estado_bl', 'alias'=>'id_estado_bl', 'filtro'=>FILTRO_ESTADOBL, 'tabla'=>'estado_bl', 'nombre'=>_TABESTADOBL, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_empresa', 'alias'=>'id_empresa', 'filtro'=>FILTRO_NIT, 'tabla'=>'empresa', 'nombre'=>_NIT, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'empresa.id_ciudad', 'alias'=>'emp_id_ciudad', 'filtro'=>FILTRO_CIUDAD, 'tabla'=>'ciudad', 'nombre'=>_TABCIUDAD, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarExp[] = array('campo'=>'empresa.id_departamento', 'alias'=>'emp_id_departamento', 'filtro'=>FILTRO_DEPARTAMENTO, 'tabla'=>'departamento', 'nombre'=>_TABDEPTO, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarExp[] = array('campo'=>'sob.id_intermediario_pais', 'alias'=>'id_intermediario_pais', 'filtro'=>FILTRO_EMPRESANOTIFICADA, 'tabla'=>'intermediario_pais', 'nombre'=>_TABEMPRESANOTIFICADA, 'opcional'=>1, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_puerto', 'alias'=>'id_puerto', 'filtro'=>FILTRO_SOLOPUERTO, 'tabla'=>'puerto', 'nombre'=>_TABPUERTO, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_muelle', 'alias'=>'id_muelle', 'filtro'=>FILTRO_MUELLE, 'tabla'=>'muelle', 'nombre'=>_TABMUELLE, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_pais_puerto_ext', 'alias'=>'id_pais_puerto_ext', 'filtro'=>FILTRO_SOLOPAIS, 'tabla'=>'paises', 'nombre'=>_TABPAISPTOEXT, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarExp[] = array('campo'=>'sob.id_puerto_ext', 'alias'=>'id_puerto_ext', 'filtro'=>FILTRO_PAISPUERTOEXT, 'tabla'=>'ciudad', 'nombre'=>_TABPTOEXT, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarExp[] = array('campo'=>'sob.id_naviera', 'alias'=>'id_naviera', 'filtro'=>FILTRO_NAVIERA, 'tabla'=>'naviera', 'nombre'=>_TABNAVIERA, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarExp[] = array('campo'=>'sob.id_agente_naviero', 'alias'=>'id_agente_naviero', 'filtro'=>FILTRO_AGENTENAVIERO, 'tabla'=>'agente_naviero', 'nombre'=>_TABAGENTENAV, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_motonave', 'alias'=>'id_motonave', 'filtro'=>FILTRO_MOTONAVE, 'tabla'=>'motonave', 'nombre'=>_TABMOTONAVE, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_consolidador', 'alias'=>'id_consolidador', 'filtro'=>FILTRO_CONSOLIDADOR, 'tabla'=>'consolidador', 'nombre'=>_TABCONSOLI, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_consolidado', 'alias'=>'id_consolidado', 'filtro'=>FILTRO_CONSOLIDADO, 'tabla'=>'consolidado', 'nombre'=>_TABCONSOLIDADO, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarExp[] = array('campo'=>'sob.id_otm', 'alias'=>'id_otm', 'filtro'=>FILTRO_OTM, 'tabla'=>'otm', 'nombre'=>_TABOTM, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_empresa_ext', 'alias'=>'id_empresa_ext', 'filtro'=>FILTRO_EMPRESAEXT, 'tabla'=>'empresa_ext', 'nombre'=>_TABEMPRESAEXT, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_ciudad_pro_dest_ext', 'alias'=>'id_ciudad_pro_dest_ext', 'filtro'=>FILTRO_CIUDADPRODESTEXT, 'tabla'=>'ciudad', 'nombre'=>_TABCIUPRODESTEXT, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarExp[] = array('campo'=>'sob.id_tipo_estiba', 'alias'=>'id_tipo_estiba', 'filtro'=>FILTRO_TIPOESTIBA, 'tabla'=>'tipo_estiba', 'nombre'=>_TABTIPOEST, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_embalaje', 'alias'=>'id_embalaje', 'filtro'=>FILTRO_EMBALAJE, 'tabla'=>'embalaje', 'nombre'=>_TABUNIDAD, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_subpartida', 'alias'=>'id_subpartida', 'filtro'=>FILTRO_CODARMONIZADO, 'tabla'=>'subpartida', 'nombre'=>_CODARMONIZADO, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_bigint');
$filtrosSismarExp[] = array('campo'=>'sob.descripcion_prod', 'alias'=>'descripcion_prod', 'filtro'=>FILTRO_DESCRIPCIONPROD, 'tabla'=>'fulltext', 'nombre'=>_TABDESCRIPCIONBL, 'opcional'=>1, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');
//$filtrosSismarExp[] = array('campo'=>'sob.id_puerto', 'alias'=>'id_puerto', 'filtro'=>FILTRO_PUERTO, 'tabla'=>'puerto', 'nombre'=>_TABPUERTOMUELLE, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_ciudad_pro_dest_pais', 'alias'=>'id_ciudad_pro_dest_pais', 'filtro'=>FILTRO_CIUDADPRODEST, 'tabla'=>'ciudad', 'nombre'=>_TABCIUPRODESTCOL, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarExp[] = array('campo'=>'sob.id_depto_pro_dest_pais', 'alias'=>'id_depto_pro_dest_pais', 'filtro'=>FILTRO_DEPTOPRODESTCOL, 'tabla'=>'departamento', 'nombre'=>_TABDEPTOPRODESTCOL, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarExp[] = array('campo'=>'sob.id_tipo_bl', 'alias'=>'id_tipo_bl', 'filtro'=>FILTRO_TIPOBL, 'tabla'=>'tipo_bl', 'nombre'=>_TABTIPOBL, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_clase_flete', 'alias'=>'id_clase_flete', 'filtro'=>FILTRO_CLASEFLETE, 'tabla'=>'clase_flete', 'nombre'=>_TABCLASFLETE, 'opcional'=>1, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_string');
$filtrosSismarExp[] = array('campo'=>'sob.id_transito', 'alias'=>'id_transito', 'filtro'=>FILTRO_TRANSITO, 'tabla'=>'transito', 'nombre'=>_TABTRANSITO, 'opcional'=>1, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_zona_franca', 'alias'=>'id_zona_franca', 'filtro'=>FILTRO_ZONAFRANCA, 'tabla'=>'zona_franca', 'nombre'=>_TABZONAF, 'opcional'=>1, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_ciiu', 'alias'=>'id_ciiu', 'filtro'=>FILTRO_CIIU, 'tabla'=>'ciiu', 'nombre'=>_CIIU, 'opcional'=>1, 'enacumulado'=>1, 'sphinx_attr'=>'sql_attr_uint');
$filtrosSismarExp[] = array('campo'=>'sob.id_cuode', 'alias'=>'id_cuode', 'filtro'=>FILTRO_CUODE, 'tabla'=>'cuode', 'nombre'=>_CUODE, 'opcional'=>1, 'enacumulado'=>0, 'sphinx_attr'=>'sql_attr_uint');

$filtrosIntercambioSismar[0] = $filtrosSismarImp;
$filtrosIntercambioSismar[1] = $filtrosSismarExp;

$tablasAux[0][] = array("tabla"=>"agente_naviero", "join"=>"sob.id_agente_naviero = agente_naviero.id_agente_naviero");
$tablasAux[0][] = array("tabla"=>"capitulo", "join"=>"sob.id_capitulo = capitulo.id_capitulo");
$tablasAux[0][] = array("tabla"=>"ciiu", "join"=>"sob.id_ciiu = ciiu.id_ciiu");
$tablasAux[0][] = array("tabla"=>"ciudad AS ciudad_pro_dest_ext", "join"=>"sob.id_ciudad_pro_dest_ext = ciudad_pro_dest_ext.id_ciudad ");
$tablasAux[0][] = array("tabla"=>"ciudad AS ciudad_pro_dest_pais", "join"=>"sob.id_ciudad_pro_dest_pais = ciudad_pro_dest_pais.id_ciudad ");
$tablasAux[0][] = array("tabla"=>"clase_bl", "join"=>"sob.id_clase_bl = clase_bl.id_clase_bl");
$tablasAux[0][] = array("tabla"=>"clase_flete", "join"=>"sob.id_clase_flete = clase_flete.id_clase_flete");
$tablasAux[0][] = array("tabla"=>"consolidado", "join"=>"sob.id_consolidado = consolidado.id_consolidado");
$tablasAux[0][] = array("tabla"=>"consolidador", "join"=>"sob.id_consolidador = consolidador.id_consolidador");
$tablasAux[0][] = array("tabla"=>"consolidador AS consolidador_nieto", "join"=>"sob.id_consolidador_nieto = consolidador_nieto.id_consolidador ");
$tablasAux[0][] = array("tabla"=>"cuode", "join"=>"sob.id_cuode = cuode.id_cuode");
$tablasAux[0][] = array("tabla"=>"deposito", "join"=>"sob.id_deposito = deposito.id_deposito");
$tablasAux[0][] = array("tabla"=>"departamento AS depto_pro_dest_pais", "join"=>"sob.id_depto_pro_dest_pais = depto_pro_dest_pais.id_departamento ");
$tablasAux[0][] = array("tabla"=>"embalaje", "join"=>"sob.id_embalaje = embalaje.id_embalaje");
$tablasAux[0][] = array("tabla"=>"empresa", "join"=>"sob.id_empresa = empresa.id_empresa");
$tablasAux[0][] = array("tabla"=>"empresa_ext", "join"=>"sob.id_empresa_ext = empresa_ext.id_empresa_ext");
$tablasAux[0][] = array("tabla"=>"estado_bl", "join"=>"sob.id_estado_bl = estado_bl.id_estado_bl");
$tablasAux[0][] = array("tabla"=>"intermediario_pais", "join"=>"sob.id_intermediario_pais = intermediario_pais.id_intermediario_pais");
$tablasAux[0][] = array("tabla"=>"motonave", "join"=>"sob.id_motonave = motonave.id_motonave");
$tablasAux[0][] = array("tabla"=>"muelle", "join"=>"sob.id_muelle = muelle.id_muelle");
$tablasAux[0][] = array("tabla"=>"naviera", "join"=>"sob.id_naviera = naviera.id_naviera");
$tablasAux[0][] = array("tabla"=>"otm", "join"=>"sob.id_otm = otm.id_otm");
$tablasAux[0][] = array("tabla"=>"paises AS pais_ciudad_pro_dest_ext", "join"=>"sob.id_pais_ciudad_pro_dest_ext = pais_ciudad_pro_dest_ext.id_paises ");
$tablasAux[0][] = array("tabla"=>"paises AS pais_puerto_ext", "join"=>"sob.id_pais_puerto_ext = pais_puerto_ext.id_paises ");
$tablasAux[0][] = array("tabla"=>"puerto", "join"=>"sob.id_puerto = puerto.id_puerto");
$tablasAux[0][] = array("tabla"=>"ciudad AS puerto_ext", "join"=>"sob.id_puerto_ext = puerto_ext.id_ciudad ");
$tablasAux[0][] = array("tabla"=>"ciudad AS puerto_transbordo", "join"=>"sob.id_puerto_transbordo = puerto_transbordo.id_ciudad ");
$tablasAux[0][] = array("tabla"=>"sia", "join"=>"sob.id_sia = sia.id_sia");
$tablasAux[0][] = array("tabla"=>"subpartida", "join"=>"sob.id_subpartida = subpartida.id_subpartida");
$tablasAux[0][] = array("tabla"=>"tipo_bl", "join"=>"sob.id_tipo_bl = tipo_bl.id_tipo_bl");
$tablasAux[0][] = array("tabla"=>"tipo_estiba", "join"=>"sob.id_tipo_estiba = tipo_estiba.id_tipo_estiba");
$tablasAux[0][] = array("tabla"=>"transito", "join"=>"sob.id_transito = transito.id_transito");
$tablasAux[0][] = array("tabla"=>"zona_franca", "join"=>"sob.id_zona_franca = zona_franca.id_zona_franca");

$tablasAux[1][] = array("tabla"=>"agente_naviero", "join"=>"sob.id_agente_naviero = agente_naviero.id_agente_naviero");
$tablasAux[1][] = array("tabla"=>"capitulo", "join"=>"sob.id_capitulo = capitulo.id_capitulo");
$tablasAux[1][] = array("tabla"=>"ciiu", "join"=>"sob.id_ciiu = ciiu.id_ciiu");
$tablasAux[1][] = array("tabla"=>"ciudad AS ciudad_pro_dest_ext", "join"=>"sob.id_ciudad_pro_dest_ext = ciudad_pro_dest_ext.id_ciudad ");
$tablasAux[1][] = array("tabla"=>"ciudad AS ciudad_pro_dest_pais", "join"=>"sob.id_ciudad_pro_dest_pais = ciudad_pro_dest_pais.id_ciudad ");
$tablasAux[1][] = array("tabla"=>"clase_bl", "join"=>"sob.id_clase_bl = clase_bl.id_clase_bl");
$tablasAux[1][] = array("tabla"=>"clase_flete", "join"=>"sob.id_clase_flete = clase_flete.id_clase_flete");
$tablasAux[1][] = array("tabla"=>"consolidado", "join"=>"sob.id_consolidado = consolidado.id_consolidado");
$tablasAux[1][] = array("tabla"=>"consolidador", "join"=>"sob.id_consolidador = consolidador.id_consolidador");
$tablasAux[1][] = array("tabla"=>"consolidador AS consolidador_nieto", "join"=>"sob.id_consolidador_nieto = consolidador_nieto.id_consolidador ");
$tablasAux[1][] = array("tabla"=>"cuode", "join"=>"sob.id_cuode = cuode.id_cuode");
$tablasAux[1][] = array("tabla"=>"deposito", "join"=>"sob.id_deposito = deposito.id_deposito");
$tablasAux[1][] = array("tabla"=>"departamento AS depto_pro_dest_pais", "join"=>"sob.id_depto_pro_dest_pais = depto_pro_dest_pais.id_departamento ");
$tablasAux[1][] = array("tabla"=>"embalaje", "join"=>"sob.id_embalaje = embalaje.id_embalaje");
$tablasAux[1][] = array("tabla"=>"empresa", "join"=>"sob.id_empresa = empresa.id_empresa");
$tablasAux[1][] = array("tabla"=>"empresa_ext", "join"=>"sob.id_empresa_ext = empresa_ext.id_empresa_ext");
$tablasAux[1][] = array("tabla"=>"estado_bl", "join"=>"sob.id_estado_bl = estado_bl.id_estado_bl");
$tablasAux[1][] = array("tabla"=>"intermediario_pais", "join"=>"sob.id_intermediario_pais = intermediario_pais.id_intermediario_pais");
$tablasAux[1][] = array("tabla"=>"motonave", "join"=>"sob.id_motonave = motonave.id_motonave");
$tablasAux[1][] = array("tabla"=>"muelle", "join"=>"sob.id_muelle = muelle.id_muelle");
$tablasAux[1][] = array("tabla"=>"naviera", "join"=>"sob.id_naviera = naviera.id_naviera");
$tablasAux[1][] = array("tabla"=>"otm", "join"=>"sob.id_otm = otm.id_otm");
$tablasAux[1][] = array("tabla"=>"paises AS pais_ciudad_pro_dest_ext", "join"=>"sob.id_pais_ciudad_pro_dest_ext = pais_ciudad_pro_dest_ext.id_paises ");
$tablasAux[1][] = array("tabla"=>"paises AS pais_puerto_ext", "join"=>"sob.id_pais_puerto_ext = pais_puerto_ext.id_paises ");
$tablasAux[1][] = array("tabla"=>"puerto", "join"=>"sob.id_puerto = puerto.id_puerto");
$tablasAux[1][] = array("tabla"=>"ciudad AS puerto_ext", "join"=>"sob.id_puerto_ext = puerto_ext.id_ciudad ");
$tablasAux[1][] = array("tabla"=>"ciudad AS puerto_transbordo", "join"=>"sob.id_puerto_transbordo = puerto_transbordo.id_ciudad ");
$tablasAux[1][] = array("tabla"=>"sia", "join"=>"sob.id_sia = sia.id_sia");
$tablasAux[1][] = array("tabla"=>"subpartida", "join"=>"sob.id_subpartida = subpartida.id_subpartida");
$tablasAux[1][] = array("tabla"=>"tipo_bl", "join"=>"sob.id_tipo_bl = tipo_bl.id_tipo_bl");
$tablasAux[1][] = array("tabla"=>"tipo_estiba", "join"=>"sob.id_tipo_estiba = tipo_estiba.id_tipo_estiba");
$tablasAux[1][] = array("tabla"=>"transito", "join"=>"sob.id_transito = transito.id_transito");
$tablasAux[1][] = array("tabla"=>"zona_franca", "join"=>"sob.id_zona_franca = zona_franca.id_zona_franca");


$tablasAuxAcum[0][] = array("tabla"=>"agente_naviero", "join"=>"sob.id_agente_naviero = agente_naviero.id_agente_naviero");
$tablasAuxAcum[0][] = array("tabla"=>"capitulo", "join"=>"sob.id_capitulo = capitulo.id_capitulo");
$tablasAuxAcum[0][] = array("tabla"=>"ciiu", "join"=>"sob.id_ciiu = ciiu.id_ciiu");
$tablasAuxAcum[0][] = array("tabla"=>"ciudad AS ciudad_pro_dest_pais", "join"=>"sob.id_ciudad_pro_dest_pais = ciudad_pro_dest_pais.id_ciudad ");
$tablasAuxAcum[0][] = array("tabla"=>"clase_bl", "join"=>"sob.id_clase_bl = clase_bl.id_clase_bl");
$tablasAuxAcum[0][] = array("tabla"=>"consolidado", "join"=>"sob.id_consolidado = consolidado.id_consolidado");
$tablasAuxAcum[0][] = array("tabla"=>"consolidador", "join"=>"sob.id_consolidador = consolidador.id_consolidador");
$tablasAuxAcum[0][] = array("tabla"=>"cuode", "join"=>"sob.id_cuode = cuode.id_cuode");
$tablasAuxAcum[0][] = array("tabla"=>"deposito", "join"=>"sob.id_deposito = deposito.id_deposito");
$tablasAuxAcum[0][] = array("tabla"=>"departamento AS depto_pro_dest_pais", "join"=>"sob.id_depto_pro_dest_pais = depto_pro_dest_pais.id_departamento ");
$tablasAuxAcum[0][] = array("tabla"=>"embalaje", "join"=>"sob.id_embalaje = embalaje.id_embalaje");
$tablasAuxAcum[0][] = array("tabla"=>"empresa", "join"=>"sob.id_empresa = empresa.id_empresa");
$tablasAuxAcum[0][] = array("tabla"=>"empresa_ext", "join"=>"sob.id_empresa_ext = empresa_ext.id_empresa_ext");
$tablasAuxAcum[0][] = array("tabla"=>"estado_bl", "join"=>"sob.id_estado_bl = estado_bl.id_estado_bl");
$tablasAuxAcum[0][] = array("tabla"=>"motonave", "join"=>"sob.id_motonave = motonave.id_motonave");
$tablasAuxAcum[0][] = array("tabla"=>"muelle", "join"=>"sob.id_muelle = muelle.id_muelle");
$tablasAuxAcum[0][] = array("tabla"=>"naviera", "join"=>"sob.id_naviera = naviera.id_naviera");
$tablasAuxAcum[0][] = array("tabla"=>"otm", "join"=>"sob.id_otm = otm.id_otm");
$tablasAuxAcum[0][] = array("tabla"=>"paises AS pais_puerto_ext", "join"=>"sob.id_pais_puerto_ext = pais_puerto_ext.id_paises ");
$tablasAuxAcum[0][] = array("tabla"=>"puerto", "join"=>"sob.id_puerto = puerto.id_puerto");
$tablasAuxAcum[0][] = array("tabla"=>"ciudad AS puerto_ext", "join"=>"sob.id_puerto_ext = puerto_ext.id_ciudad ");
$tablasAuxAcum[0][] = array("tabla"=>"subpartida", "join"=>"sob.id_subpartida = subpartida.id_subpartida");
$tablasAuxAcum[0][] = array("tabla"=>"tipo_bl", "join"=>"sob.id_tipo_bl = tipo_bl.id_tipo_bl");
$tablasAuxAcum[0][] = array("tabla"=>"tipo_estiba", "join"=>"sob.id_tipo_estiba = tipo_estiba.id_tipo_estiba");

$tablasAuxAcum[1][] = array("tabla"=>"agente_naviero", "join"=>"sob.id_agente_naviero = agente_naviero.id_agente_naviero");
$tablasAuxAcum[1][] = array("tabla"=>"capitulo", "join"=>"sob.id_capitulo = capitulo.id_capitulo");
$tablasAuxAcum[1][] = array("tabla"=>"ciiu", "join"=>"sob.id_ciiu = ciiu.id_ciiu");
$tablasAuxAcum[1][] = array("tabla"=>"ciudad AS ciudad_pro_dest_pais", "join"=>"sob.id_ciudad_pro_dest_pais = ciudad_pro_dest_pais.id_ciudad ");
$tablasAuxAcum[1][] = array("tabla"=>"clase_bl", "join"=>"sob.id_clase_bl = clase_bl.id_clase_bl");
$tablasAuxAcum[1][] = array("tabla"=>"consolidado", "join"=>"sob.id_consolidado = consolidado.id_consolidado");
$tablasAuxAcum[1][] = array("tabla"=>"consolidador", "join"=>"sob.id_consolidador = consolidador.id_consolidador");
$tablasAuxAcum[1][] = array("tabla"=>"cuode", "join"=>"sob.id_cuode = cuode.id_cuode");
$tablasAuxAcum[1][] = array("tabla"=>"deposito", "join"=>"sob.id_deposito = deposito.id_deposito");
$tablasAuxAcum[1][] = array("tabla"=>"departamento AS depto_pro_dest_pais", "join"=>"sob.id_depto_pro_dest_pais = depto_pro_dest_pais.id_departamento ");
$tablasAuxAcum[1][] = array("tabla"=>"embalaje", "join"=>"sob.id_embalaje = embalaje.id_embalaje");
$tablasAuxAcum[1][] = array("tabla"=>"empresa", "join"=>"sob.id_empresa = empresa.id_empresa");
$tablasAuxAcum[1][] = array("tabla"=>"empresa_ext", "join"=>"sob.id_empresa_ext = empresa_ext.id_empresa_ext");
$tablasAuxAcum[1][] = array("tabla"=>"estado_bl", "join"=>"sob.id_estado_bl = estado_bl.id_estado_bl");
$tablasAuxAcum[1][] = array("tabla"=>"motonave", "join"=>"sob.id_motonave = motonave.id_motonave");
$tablasAuxAcum[1][] = array("tabla"=>"muelle", "join"=>"sob.id_muelle = muelle.id_muelle");
$tablasAuxAcum[1][] = array("tabla"=>"naviera", "join"=>"sob.id_naviera = naviera.id_naviera");
$tablasAuxAcum[1][] = array("tabla"=>"otm", "join"=>"sob.id_otm = otm.id_otm");
$tablasAuxAcum[1][] = array("tabla"=>"paises AS pais_puerto_ext", "join"=>"sob.id_pais_puerto_ext = pais_puerto_ext.id_paises ");
$tablasAuxAcum[1][] = array("tabla"=>"puerto", "join"=>"sob.id_puerto = puerto.id_puerto");
$tablasAuxAcum[1][] = array("tabla"=>"ciudad AS puerto_ext", "join"=>"sob.id_puerto_ext = puerto_ext.id_ciudad ");
$tablasAuxAcum[1][] = array("tabla"=>"subpartida", "join"=>"sob.id_subpartida = subpartida.id_subpartida");
$tablasAuxAcum[1][] = array("tabla"=>"tipo_bl", "join"=>"sob.id_tipo_bl = tipo_bl.id_tipo_bl");
$tablasAuxAcum[1][] = array("tabla"=>"tipo_estiba", "join"=>"sob.id_tipo_estiba = tipo_estiba.id_tipo_estiba");