-- MySQL Script generated by MySQL Workbench
-- 01/06/15 15:22:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema min_agricultura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema min_agricultura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `min_agricultura` DEFAULT CHARACTER SET utf8 ;
USE `min_agricultura` ;

-- -----------------------------------------------------
-- Table `min_agricultura`.`acuerdo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `min_agricultura`.`acuerdo` ;

CREATE TABLE IF NOT EXISTS `min_agricultura`.`acuerdo` (
  `acuerdo_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `acuerdo_nombre` VARCHAR(100) NOT NULL,
  `acuerdo_descripcion` TEXT NOT NULL,
  `acuerdo_intercambio` ENUM('impo','expo') NOT NULL,
  `acuerdo_fvigente` DATE NOT NULL,
  `acuerdo_uinsert` INT(10) UNSIGNED NOT NULL,
  `acuerdo_finsert` DATETIME NOT NULL,
  `acuerdo_uupdate` INT(10) UNSIGNED NOT NULL,
  `acuerdo_fupdate` DATETIME NOT NULL,
  `acuerdo_mercado_id` INT(10) UNSIGNED NOT NULL,
  `acuerdo_id_pais` SMALLINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`acuerdo_id`),
  INDEX `fk_acuerdo_mercado1_idx` (`acuerdo_mercado_id` ASC),
  INDEX `fk_acuerdo_pais1_idx` (`acuerdo_id_pais` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `min_agricultura`.`acuerdo_det`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `min_agricultura`.`acuerdo_det` ;

CREATE TABLE IF NOT EXISTS `min_agricultura`.`acuerdo_det` (
  `acuerdo_det_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `acuerdo_det_arancel_base` SMALLINT(5) NOT NULL,
  `acuerdo_det_productos` TEXT NOT NULL,
  `acuerdo_det_productos_desc` VARCHAR(45) NOT NULL,
  `acuerdo_det_administracion` TEXT NOT NULL,
  `acuerdo_det_administrador` VARCHAR(150) NOT NULL,
  `acuerdo_det_nperiodos` SMALLINT(4) UNSIGNED NOT NULL,
  `acuerdo_det_acuerdo_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`acuerdo_det_id`, `acuerdo_det_acuerdo_id`),
  INDEX `fk_acuerdo_det_acuerdo_idx` (`acuerdo_det_acuerdo_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `min_agricultura`.`contingente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `min_agricultura`.`contingente` ;

CREATE TABLE IF NOT EXISTS `min_agricultura`.`contingente` (
  `contingente_id` INT(10) UNSIGNED NOT NULL,
  `contingente_id_pais` SMALLINT(3) UNSIGNED NOT NULL,
  `contingente_acumulado_pais` ENUM('0','1') NULL,
  `contingente_mcontingente` ENUM('0','1') NOT NULL,
  `contingente_desc` TEXT NOT NULL,
  `contingente_acuerdo_det_id` INT(10) UNSIGNED NOT NULL,
  `contingente_acuerdo_det_acuerdo_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`contingente_id`, `contingente_acuerdo_det_id`, `contingente_acuerdo_det_acuerdo_id`),
  INDEX `fk_contingente_acuerdo_det1_idx` (`contingente_acuerdo_det_id` ASC, `contingente_acuerdo_det_acuerdo_id` ASC),
  INDEX `fk_contingente_pais1_idx` (`contingente_id_pais` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `min_agricultura`.`contingente_det`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `min_agricultura`.`contingente_det` ;

CREATE TABLE IF NOT EXISTS `min_agricultura`.`contingente_det` (
  `contingente_det_id` INT(10) UNSIGNED NOT NULL,
  `contingente_det_anio_ini` SMALLINT(4) UNSIGNED NOT NULL,
  `contingente_det_anio_fin` SMALLINT(4) UNSIGNED NOT NULL,
  `contingente_det_peso_neto` FLOAT(13,2) UNSIGNED NOT NULL,
  `contingente_det_contingente_id` INT(10) UNSIGNED NOT NULL,
  `contingente_det_contingente_acuerdo_det_id` INT(10) UNSIGNED NOT NULL,
  `contingente_det_contingente_acuerdo_det_acuerdo_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`contingente_det_id`, `contingente_det_contingente_id`, `contingente_det_contingente_acuerdo_det_id`, `contingente_det_contingente_acuerdo_det_acuerdo_id`),
  INDEX `fk_contingente_det_contingente1_idx` (`contingente_det_contingente_id` ASC, `contingente_det_contingente_acuerdo_det_id` ASC, `contingente_det_contingente_acuerdo_det_acuerdo_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `min_agricultura`.`salvaguardia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `min_agricultura`.`salvaguardia` ;

CREATE TABLE IF NOT EXISTS `min_agricultura`.`salvaguardia` (
  `salvaguardia_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `salvaguardia_msalvaguardia` ENUM('0','1') NOT NULL,
  `salvaguardia_contingente_id` INT(10) UNSIGNED NOT NULL,
  `salvaguardia_contingente_acuerdo_det_id` INT(10) UNSIGNED NOT NULL,
  `salvaguardia_contingente_acuerdo_det_acuerdo_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`salvaguardia_id`, `salvaguardia_contingente_id`, `salvaguardia_contingente_acuerdo_det_id`, `salvaguardia_contingente_acuerdo_det_acuerdo_id`),
  INDEX `fk_salvaguardia_contingente1_idx` (`salvaguardia_contingente_id` ASC, `salvaguardia_contingente_acuerdo_det_id` ASC, `salvaguardia_contingente_acuerdo_det_acuerdo_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `min_agricultura`.`salvaguardia_det`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `min_agricultura`.`salvaguardia_det` ;

CREATE TABLE IF NOT EXISTS `min_agricultura`.`salvaguardia_det` (
  `salvaguardia_det_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `salvaguardia_det_anio_ini` SMALLINT(4) UNSIGNED NOT NULL,
  `salvaguardia_det_anio_fin` SMALLINT(4) UNSIGNED NOT NULL,
  `salvaguardia_det_peso_neto` FLOAT(13,2) UNSIGNED NOT NULL,
  `salvaguardia_det_salvaguardia_id` INT UNSIGNED NOT NULL,
  `salvaguardia_det_salvaguardia_contingente_id` INT(10) UNSIGNED NOT NULL,
  `salvaguardia_det_salvaguardia_contingente_acuerdo_det_id` INT(10) UNSIGNED NOT NULL,
  `salvaguardia_det_salvaguardia_contingente_acuerdo_det_acuerdo_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`salvaguardia_det_id`, `salvaguardia_det_salvaguardia_id`, `salvaguardia_det_salvaguardia_contingente_id`, `salvaguardia_det_salvaguardia_contingente_acuerdo_det_id`, `salvaguardia_det_salvaguardia_contingente_acuerdo_det_acuerdo_id`),
  INDEX `fk_salvaguardia_det_salvaguardia1_idx` (`salvaguardia_det_salvaguardia_id` ASC, `salvaguardia_det_salvaguardia_contingente_id` ASC, `salvaguardia_det_salvaguardia_contingente_acuerdo_det_id` ASC, `salvaguardia_det_salvaguardia_contingente_acuerdo_det_acuerdo_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `min_agricultura`.`desgravacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `min_agricultura`.`desgravacion` ;

CREATE TABLE IF NOT EXISTS `min_agricultura`.`desgravacion` (
  `desgravacion_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `desgravacion_desc` TEXT NOT NULL,
  `desgravacion_acuerdo_det_id` INT(10) UNSIGNED NOT NULL,
  `desgravacion_acuerdo_det_acuerdo_id` INT(10) UNSIGNED NOT NULL,
  `desgravacion_id_pais` SMALLINT(3) UNSIGNED NOT NULL,
  `desgravacion_mdesgravacion` ENUM('0','1') NOT NULL,
  `desgravacion_nperiodos` SMALLINT(4) NULL,
  `desgravacion_col` VARCHAR(45) NULL,
  PRIMARY KEY (`desgravacion_id`, `desgravacion_acuerdo_det_id`, `desgravacion_acuerdo_det_acuerdo_id`),
  INDEX `fk_desgravacion_acuerdo_det1_idx` (`desgravacion_acuerdo_det_id` ASC, `desgravacion_acuerdo_det_acuerdo_id` ASC),
  INDEX `fk_desgravacion_pais1_idx` (`desgravacion_id_pais` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `min_agricultura`.`desgravacion_det`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `min_agricultura`.`desgravacion_det` ;

CREATE TABLE IF NOT EXISTS `min_agricultura`.`desgravacion_det` (
  `desgravacion_det_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `desgravacion_det_anio_ini` SMALLINT(4) UNSIGNED NOT NULL,
  `desgravacion_det_anio_fin` SMALLINT(4) UNSIGNED NOT NULL,
  `desgravacion_det_tasa` SMALLINT(2) UNSIGNED NOT NULL,
  `desgravacion_det_desgravacion_id` INT UNSIGNED NOT NULL,
  `desgravacion_det_desgravacion_acuerdo_det_id` INT(10) UNSIGNED NOT NULL,
  `desgravacion_det_desgravacion_acuerdo_det_acuerdo_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`desgravacion_det_id`, `desgravacion_det_desgravacion_id`, `desgravacion_det_desgravacion_acuerdo_det_id`, `desgravacion_det_desgravacion_acuerdo_det_acuerdo_id`),
  INDEX `fk_desgravacion_det_desgravacion1_idx` (`desgravacion_det_desgravacion_id` ASC, `desgravacion_det_desgravacion_acuerdo_det_id` ASC, `desgravacion_det_desgravacion_acuerdo_det_acuerdo_id` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
