LOAD DATA LOCAL INFILE 'C:/Users/FabianAndres/Downloads/data_madr/Exp2014-new.csv'
INTO TABLE declaraexp_load
CHARACTER SET utf8
FIELDS TERMINATED BY '|'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n' STARTING BY ''


